### ISSUE TITLE
[QA] ERD 조회

### ISSUE THREAD

**Issue by hobby3530** [nhnacademy-be4-ckin/ckin-management#52]
### 발견 시간 : 2024-03-26 (화)
CKIN 홈페이지 footer 에 있는 erd 링크로 들어가도 erd 가 보이지 않아요.
권한 문제인 것 같은데 공개 범위를 바꾸는 것은 어떤가요?

**Comment by f1v3-dev** [comment]
수정하였습니다 🙇🏻‍♂️
