### ISSUE TITLE
[QA] 주문 시 포인트 사용

### ISSUE THREAD

**Issue by hobby3530** [nhnacademy-be4-ckin/ckin-management#59]
### 발견 시간 : 2024-03-26 (화)

주문 시 보유중인 포인트를 조작한 후, 포인트를 입력하면 보유한 포인트보다 더 많은 포인트를 사용할 수 있는 것 같습니다
주문이나 결제 시 검증 로직이 추가되면 좋을 것 같습니다 ㅎㅎ

![Image](https://github.com/nhnacademy-be4-ckin/ckin-management/assets/76966467/790c0307-5675-4de1-b439-b4d15d1c1a68)

**Comment by f1v3-dev** [comment]
주문 완료시 보유 포인트보다 많은 금액을 사용하지 못하도록 처리하였습니다.
또한, 포인트 단위가 제대로 보이지 않는 것도 Front 쪽에서 처리하였습니다.
