### ISSUE TITLE
[QA] 마이페이지 주문 상세 뷰

### ISSUE THREAD

**Issue by hobby3530** [nhnacademy-be4-ckin/ckin-management#60]
### 발견 시간 : 2024-03-26 (화)
주문 상세 뷰에서 배송 상태를 보여줄 때 상태값을 그대로 보여주는 것 같습니다!
예를 들어 READY 상태는 배송 준비 중으로 바꾸어서 보여주는 것은 어떨까요?

![Image](https://github.com/nhnacademy-be4-ckin/ckin-management/assets/76966467/7fde9ded-a141-43d7-8b4b-f0c843873f8c)

**Comment by f1v3-dev** [comment]
수정하였습니다 🙇🏻‍♂️
